name: kkeutgong_mobile
description: "끝공 - AI 기반 자격증 학습 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  freezed_annotation: ^3.1.0
  get: ^4.7.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  intl: ^0.20.0

  # Auth
  flutter_secure_storage: ^9.2.0
  kakao_flutter_sdk_user: ^1.9.0
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^6.1.0

  # Settings / Info
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

  # Monitoring
  sentry_flutter: ^8.10.0

  # Notifications
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen: ^5.11.0
  freezed: ^3.2.0
  rename: ^3.1.0
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_gen_runner: ^5.11.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/config/.env
  fonts:
    - family: SeoulAlrim
      fonts:
        - asset: assets/fonts/SeoulAlrim-Bold.ttf
          weight: 700
        - asset: assets/fonts/SeoulAlrim-ExtraBold.ttf
          weight: 800
    - family: TossFace
      fonts:
        - asset: assets/fonts/TossFace.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
